package com.example.publickeyinfrastructure.model;

public enum ExtensionType {
    SUBJECT_ALTERNATIVE_NAME,
    KEY_USAGE,
    EXTENDED_KEY_USAGE,
    BASIC_CONSTRAINTS,
    CERTIFICATE_POLICIES,
    AUTHORITY_KEY_IDENTIFIER,
    SUBJECT_KEY_IDENTIFIER,
    CRL_DISTRIBUTION_POINTS,
    AUTHORITY_INFORMATION_ACCESS,
    CUSTOM
}